name: 'Terraform Testing and Release'
on:
  - push
env:
  tf_version: 'latest'
  tf_working_dir: '.'
  AWS_DEFAULT_REGION: 'us-east-2'
jobs:
  terraform:
    name: 'Terraform Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: 'Create Tag'
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
